// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountry = "countries"

// Country mapped from table <countries>
type Country struct {
	ID     string `gorm:"column:id;primaryKey;default:uuid()" json:"id"`
	Name   string `gorm:"column:name" json:"name"`
	Lang   string `gorm:"column:lang" json:"lang"`
	Region string `gorm:"column:region" json:"region"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
