// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLetter = "letters"

// Letter mapped from table <letters>
type Letter struct {
	ID      int32     `gorm:"column:id;primaryKey" json:"id"`
	Letter  string    `gorm:"column:letter;not null" json:"letter"`
	Date    time.Time `gorm:"column:date" json:"date"`
	Lang    string    `gorm:"column:lang" json:"lang"`
	Country string    `gorm:"column:country" json:"country"`
	Region  string    `gorm:"column:region" json:"region"`
}

// TableName Letter's table name
func (*Letter) TableName() string {
	return TableNameLetter
}
