// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLetter = "letters"

// Letter mapped from table <letters>
type Letter struct {
	ID        string    `gorm:"column:id;primaryKey;default:uuid()" json:"id"`
	Letter    string    `gorm:"column:letter;not null" json:"letter"`
	CreatedAt time.Time `gorm:"column:createdAt" json:"createdAt"`
	CountryID string    `gorm:"column:countryID;index:countryID,priority:1" json:"countryID"`
	Country  Country    `gorm:"foreignkey:CountryId;references:Id"`
}

// TableName Letter's table name
func (*Letter) TableName() string {
	return TableNameLetter
}
